#!/bin/sh

# Use neovim for vim if present.

# Verbose
# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkdir="mkdir -pv" \
	jc="compile" \
	za="devour zathura" \
	lb="devour libreoffice" \
    grep="grep --color" \
    ls="lsd" \
    ll="lsd -la" \
    la="lsd -la" \
    l="lsd -l" \
    mpv="devour mpv" \
    vlc="devour vlc" \
    mu="devour mupdf" \
    emacs="devour emacs"

# shortcuts
alias \
  d="cd ~/Downloads" \
  D="cd ~/Documents" \
  p="cd ~/Pictures"

# Git
alias \
    gst="git status" \
    grhh="git reset --hard" \
    gcl="git clone"

# Package manager
alias \
    xbi="sudo vpm i" \
    xbr="sudo vpm rr" \
    xbu="sudo vpm up" \
    xbq="sudo vpm s"
