corner-radius = 5;

experimental-backends = true;
backend = "glx";

blur:
{
	method="dual_kawase";
	strength=5
};

blur-background-exclude = [
    "class_g = 'slop'",
    "class_g = 'Xfce4-screenshooter'",
    "class_g = 'discover-overlay'",
    "class_g = 'Discover-overlay'",
    "class_g = 'ulauncher'",
    "class_g = 'Ulauncher'",
    "class_g = 'org.gnome.Nautilus'",
    "class_g = 'insomnia'",
    "class_g = 'Insomnia'",
    "class_g = 'brave-browser'",
    "class_g = 'Brave-browser'"
];
