# Use yt-dlp
script-opts=ytdl_hook-ytdl_path=yt-dlp
volume=70
# ytdl-raw-options=mark-watched=,cookies=/home/athul/.config/mpv/www.youtube.com_cookies.txt,add-metadata=
ytdl-raw-options=add-metadata=,yes-playlist=
